    require ("../gentelella/vendors/bootstrap/dist/js/bootstrap.min.js");
    require ("../gentelella/vendors/fastclick/lib/fastclick.js");
    require ("../gentelella/vendors/nprogress/nprogress.js");
    require ("../gentelella/vendors/Chart.js/dist/Chart.min.js");
    require ("../gentelella/vendors/gauge.js/dist/gauge.min.js");
    require ("../gentelella/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js");
    require ("../gentelella/vendors/iCheck/icheck.min.js");
    require ("../gentelella/vendors/skycons/skycons.js");
    require ("../gentelella/vendors/Flot/jquery.flot.js");
    require ("../gentelella/vendors/Flot/jquery.flot.pie.js");
    require ("../gentelella/vendors/Flot/jquery.flot.time.js");
    require ("../gentelella/vendors/Flot/jquery.flot.stack.js");
    require ("../gentelella/vendors/Flot/jquery.flot.resize.js");
    require ("../gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js");
    require ("../gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js");
    require ("../gentelella/vendors/flot.curvedlines/curvedLines.js");
    // require ("../gentelella/vendors/DateJS/build/date.js");
    require ("../gentelella/vendors/jqvmap/dist/jquery.vmap.js");
    require ("../gentelella/vendors/jqvmap/dist/maps/jquery.vmap.world.js");
    require ("../gentelella/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js");
    // require ("../gentelella/vendors/moment/min/moment.min.js");
    // require ("../gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js");
	require	("../gentelella/build/js/custom.min.js");
    require ("../gentelella/custom.js");